# Generated by Django 4.1.5 on 2023-01-18 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='Note',
        ),
    ]
